### PR TITLE
Use regex module

### PR DESCRIPTION
**Pull request by riccardotornesello**
Preparing the submitter for Enowars 4 I noticed that the server doesn't support all regexes.
For example the problem was with \X, related with unicode.
Using the module regex instead of re solves the problem

### CODE REVIEW

**Comment by danielepusceddu** [comment]
You could've written `import regex as re` to avoid changing anything else.

**Comment by borzunov** [comment]
Hi @riccardotornesello!

This PR breaks the guarantee (mentioned in the docs) that the farm client doesn't require any Python libraries to be installed. I think this guarantee is important to be able to quickly deploy the client on any machines and environments during the competition (you won't need to resolve any version conflicts etc.), and we need very good reasons to break it.

Can you please provide more information about the flag format you've wanted to define? Can't you do this with `(?u)` expression in the built-in `re` module (that enables the [re.UNICODE](https://docs.python.org/2/library/re.html#re.U) flag)?

**Comment by TheAvidDev** [comment]
Not the original reporter, but the flag format can be seen [here](https://enowars.com/faq.html), and is `🏳️‍🌈\X{4}`. A [regex101.com link](https://regex101.com/r/dTOtW3/1) is also provided for clarity.

**Comment by borzunov** [comment]
Thank you for the links explaining the situation.

1.  I don't want to make the code more complicated because of one CTF that has already passed. Many CTFs introduce some unusual rules (like the unusual flag format), and it's okay that the farm may need changes for a particular contest. So, I will close this PR for now.

2. Still, if more CTFs require the `regex` module for searching the flags (e.g. if future ENOWARS keep the same flag format), I will agree that this feature is useful. Please write here if you encounter such CTFs :)

3. If we encounter such CTFs and decide to merge this feature, I suggest the following to avoid breaking the "farm client doesn't need additional libraries" guarantee:
    * Add a `USE_EXTENDED_REGEX` option to the farm config.
    * In the farm client, import and use the `regex` module only if this option is enabled. Keep using `re` module in other cases.

**Comment by TheAvidDev** [comment]
I agree, adding dependencies isn't a good idea when it's a goal of the project to do otherwise. Perhaps the simplest idea would be to just import whichever module exists, along the lines of:
```py
try:
    import regex as re
except ImportError:
    import re
```
This would remove the need for dependencies, and wouldn't require an option to the config -- a simple mention in the docs would do.

**Comment by borzunov** [comment]
The downside of this solution is that some team members may forget to install the `regex` module on their laptops. In this case, the farm client won't fail (`re` doesn't raise any exceptions when the expression contains `\X` or other advanced sequences) but will miss all flags.

Because of this, I think that an explicit option is necessary (if the option is enabled, the client won't silently fail if `regex` is absent).

**Comment by TheAvidDev** [comment]
Ah yep, agreed.

**Pull request closed without merging**
